
ruoli = {
    "Contadino 👨🏻‍🌾": "*Sei un contadino\\!* 👨🏻‍🌾\n\nGiochi per la fazione dei buoni\\. Seppur costretto a zappare le vigne, hai un ruolo chiave nel gioco\\."
                    "Tutti vorrebbero essere te o… si fingeranno te\\. Durante il corso della partita, puoi rivelarti il primo giorno\\!\n\n"
                    "Ma un contadino esposto subito, ricorda, è un infamon\\!\\!\n\n_Attenzione\\!\\! Il recente aggiornamento ha portato il ruolo del "
                      "maledetto ad essere 'silente'\\. Ovvero, se lo sei non lo saprai finché non verrai morso da un lupo, trasformandoti in uno "
                      "del branco\\!_",
    "Angelo Custode 👼🏻": "*Sei l'angelo custode\\!* 👼🏻\n\nGiochi per la fazione dei buoni\\. Per oggi puoi scegliere di chiamarti Raffaele, Michele "
                       "oppure Gabriele\\.\\.\\. Scherziamo\\!\nIl tuo ruolo è uno dei più importanti della partita, quindi sii prudente e non dire di "
                       "esserlo \\(non ti rivelare\\)\\.\nTi consigliamo di saltare per la prima notte, scegliere la persona sbagliata da proteggere "
                        "potrebbe essere fatale\\. Dal primo giorno presta attenzione ai ruoli vedenti \\(veggente, investigatore, vecchio saggio "
                        "o oracolo\\) che si sono esposti in partita e, dalla notte successiva, cerca di dargli la tua protezione\\.\n\n"
                       "_Consiglio\\!\\! In caso tu sia costretto a rivelarti, se non è il termine della partita, cerca un ruolo 'copertura' con "
                        "cui esporti, senza però destare sospetti\\._",
    "Osservatore 👁️": "*Sei l'osservatore\\!* 👁️\n\nnGiochi per la fazione dei buoni\\. Sei l'unico a conoscenza della vera identità del veggente, "
                     "colui che carpisce i ruoli degli altri giocatori, sii prudente e mantieni il segreto fino al momento necessario\\. "
                       "Mi raccomando, tieni aggiornati tutti sulla salute di tu\\-sai\\-chi\\. Alla sua morte conoscereai l'identità del suo "
                         "eventuale successore, anche detto apprendista\\.",
    "Veggente 👳🏼‍♂️": "*Sei il veggente\\.\\.\\.oppure credi\\!* 👳🏼‍♂️\n\nGiochi per la fazione dei buoni, in entrambi i casi\\. Nel primo in cui sei effettivamente "
                 "il Veggente, il tuo ruolo è quello di scrutare l'identità degli altri giocatori, al fine di scovare i cattivi e annunciarli "
                 "durante il giorno\\. Ci sono due vie per capire se sei effettivamente chi pensi di essere:\n\n"
                 "\\- L'osservatore ti conferma \\(è la strada più semplice e sicura\\);\n"
                 "\\- Verifichi per due volte il ruolo della medesima persona, se è uguale in ambedue le occasioni, allora sarai TU colui armato "
                   "di turbante e tarocchi, altrimenti sarai Folle, ci spiace deluderti ma le tue carte sono un po' sballate\\.\n\n"
                   "Se hai appurato di essere il Folle, presentati al bot come tale e segui i nostri consigli\\!",
    "Folle 🃏": "*Sei il folle\\!* 🃏\n\nGiochi per la fazione dei buoni\\. Verrai presentato come Veggente, come anticipato se hai letto il suo ruolo "
              "\\(sennò vattelo a recuperare\\)\\. Vedrai i ruoli in partita, che siano morti o vivi\\. Perciò non sei poi così inutile\\.\\. diciamo\\! "
                "Ogni giorno, quindi, esponi ciò che vedi a tutti gli altri\\. ",
    "Apprendista Veggente 🙇🏼‍♂️": "*Sei l'apprendista veggente\\!* 🙇🏼‍♂️\n\nGiochi per la fazione dei buoni\\. La tua esistenza implica quella del veggente, "
                             "tuttavia non sai chi è fino alla sua morte, da quel momento erediterai i suoi tarocchi e i suoi poteri passeranno "
                               "a te\\. Quando diventi veggente presentati al bot come tale e saprai come comportarti\\!  ",
    "Vecchio Saggio 📚": "*Sei il vecchio saggio\\!* 📚\n\nGiochi per la fazione dei buoni\\. Ormai giunto all'età del pensionamento usi la tua "
                       "esperienza per capire se qualcuno uccide o meno\\. Ogni GIORNO potrai selezionare un altro giocatore e capire se ha "
                        "l'indole omicida\\! Prima del linciaggio ricordati di invitare tutti a seguire il tuo voto, specificando chi in "
                         "alternativa sarà la tua patta\\. Essendo un ruolo vedente, rivelati con cautela ma non aspettare troppo\\.\n"
                         "Attenzione, però, vedrai come ruoli buoni che uccidono i seguenti:\n"
                         "\\- Artigliere;\n\\- Cacciatore del Paese/Urbano;\n\\- Cacciatore di Satanisti;\n"
                         "In ogni altra situazione, al momento del linciaggio se scruti la persona come pericolosa, linciala\\! ",
    "Investigatore 🕵️‍♂️": "*Sei l'investigatore\\!* 🕵️‍♂️\n\nGiochi per la fazione dei buoni\\. SCRUTA DI NOTTE E RIVELATI IMMEDIATAMENTE DI GIORNO, "
                     "invitando gli altri a seguirti al linciaggio e rivelando il nome del giocatore scelto sul bot\\. Considerete le buone probabilità"
                     "di essere scoperto durante le tue "
                     "investigazioni, non occorre attendere di rivelarsi\\. Piuttosto invoca l'angelo e spera ci sia per proteggerti, "
                      "nel frattempo scova più cattivi possibili ed informa il popolo\\.",
    "Oracolo 🌀": "*Sei l’oracolo\\!* 🌀\n\nGiochi per la fazione dei buoni\\.Il tuo compito è quello di NON vedere cosa gli altri sono\\. "
                "Per intenderci, saprai cosa per certo non è un giocatore, escludendo quindi la possibilità che possa essere buono o cattivo\\. "
                 "Scruti di notte, informi di giorno il popolo\\. In concomitanza con gli altri ruoli vedenti, sei importante, tuttavia è sempre "
                  "un bene rivelarsi presto, sopratutto se in partita ci sono già veggente o investigatore\\.",
    "Cacciatore del Paese 🎯": "*Sei il cacciatore del paese/urbano\\!* 🎯\n\nGiochi per la fazione dei buoni\\.\\(In partita potrai chiamarti “cacciatore di paese, "
                         "cacciapaese”\\)\\.Armato di freccette, farai di qualcuno il tuo bersaglio \\.\\. solo però in punto di morte\\. Difatti, "
                          "al momento del linciaggio o se un ruolo cattivo verrà a farti visita, potrai portare nella tomba qualcuno con te\\. "
                          "Se ad ucciderti sarà un lupo allora esso stesso sarà condannato a morte dal tuo ultimo colpo\\.  Attenzione ai ruoli "
                           "ancora in gioco, uccidi responsabilmente\\.\n\n_N\\.B\\. Verrai visto dal vecchio saggio come qualcuno che uccide, perciò "
                           "discolpati immediatamente o rivelati prima in partita\\._",
      "Cacciatore Urbano 🎯": "*Sei il cacciatore del paese/urbano\\!* 🎯\n\nGiochi per la fazione dei buoni\\.\\(In partita potrai chiamarti “cacciatore di paese, "
                         "cacciapaese”\\)\\.Armato di freccette, farai di qualcuno il tuo bersaglio \\.\\. solo però in punto di morte\\. Difatti, "
                          "al momento del linciaggio o se un ruolo cattivo verrà a farti visita, potrai portare nella tomba qualcuno con te\\. "
                          "Se ad ucciderti sarà un lupo allora esso stesso sarà condannato a morte dal tuo ultimo colpo\\.  Attenzione ai ruoli "
                           "ancora in gioco, uccidi responsabilmente\\.\n\n_N\\.B\\. Verrai visto dal vecchio saggio come qualcuno che uccide, perciò "
                           "discolpati immediatamente o rivelati prima in partita\\._",
    "Cacciatore di Satanisti 💂🏻‍♂️": "*Sei il cacciatore di Satanisti\\!* 💂\n\nGiochi per la fazione dei buoni\\. Come suggerisce il tuo titolo, "
                                "sei colui che scova i Satanisti \\(o satana, abbreviazione\\) e li uccide con una semplice visita notturna\\.\n\n"
                                "\\- Se ti fa visita stupidamente un Satanista, morirà l’ultimo ad aver aderito alla setta e conoscerai quanti "
                                "ne restano\\. Non puoi quindi essere convertito;\n "
                                "\\- Se ti fa visita il Serial Killer, muori e viceversa se vuoi prenderti un caffè con lui;\n"
                                "\\- Se visiti un lupo, quello al massimo ti canta una canzone\\. Ovvero non succede nulla;\n\n"
                                "Rivelati ad inizio partita, i lupi non ti uccideranno in quanto servi al popolo quanto a loro, "
                                "tuttavia non informare nessuno circa le tue intenzioni di visitare un giocatore, prenditi però il merito "
                                "qualora beccando un Satanista, il giorno dopo lo vedrai morto nell’elenco\\.\n\n"
                                "_N\\.B\\.  Verrai visto dal vecchio saggio con potenziale cattivo, visto il ruolo capace di uccidere\\. "
                                "Sii veloce a difenderti dalle sue eventuali accuse\\._",
    "Scudiero 🛡️": "*Sei lo scudiero\\!* 🛡️\n\nGiochi per la fazione dei buoni\\. Il tuo ruolo è correlato a quello del Cacciatore di Satanisti\\. "
                "Alla sua morte, se non sarai convertito o morto anche tu, prenderai il suo posto\\. Per conoscere le tue skills, presentati "
                 "nuovamente al bot come Cacciatore di Satanisti\\.",
    "Portatore di Tempeste 🌩️": "*Sei il portatore di tempeste\\!* 🌩️\n\nGiochi per la fazione dei buoni\\. Invita tutti a preparare l’ombrello "
                              "e rivelati durante la notte, il picchiettare incessante della pioggia e il frastuono di fulmini e saette terrà "
                               "tutti svegli, tanto da non permettere ai ruoli cattivi di fare le loro azioni notturne\\. "
                                "Sei utile da vivo, perciò non aspettare troppo a far la tua danza della pioggia, se ci finisci secco i campi "
                               "saranno aridi e la colpa sarà solo tua\\!",
    "Morfeo 💤": "*Sei Morfeo\\!* 💤\n\nGiochi per la fazione dei buoni\\. Paragonato talvolta ad un professore di matematica dell'università "
                  "hai il potere e la capacità di far addormentare tutti ed impedirgli di utilizzare le loro azioni notturne\\. Non usare "
                  "questa abilità a sproposito, fallo se non si è rivelato il fabbro se presente così sarete salvi per ben due notti\\. ",
    "Fabbro ⚒️": "*Sei il fabbro\\!* ⚒️\n\nGiochi per la fazione dei buoni\\. Ma qual è il tuo compito\\? Basta rivelarti per evitare che i lupi "
             "possano attaccare per una notte\\. D’altronde si sa, l’argento combatte i lupacchiotti\\. Appurata la veridicità del tuo ruolo, "
              "verrai confermato come “argento real / buono”, ma perderai la tua utilità, tornando vulnerabile \\(ed inutile\\) sino a prova "
              "contraria\\.\n\n"
              "_Postilla\\!\\! Il lupo imbroglione potrà fingersi te, tuttavia non avrà davvero le tue capacità\\. Se sei ancora in partita, "
              "dimostra a tutti chi sei davvero\\!_",
    "Artigliere 🔫": "*Sei l’artigliere\\!* 🔫\n\nGiochi per la fazione dei buoni\\. Hai le pistole nella Fendi, e puoi sparare due volte nel corso "
                   "della partita\\. Utilizza il tuo potere con ingegno, senza abusarne se non c’è la giusta motivazione\\. Non è d’obbligo sparare, "
                    "tuttavia se esponi il tuo ruolo, per confermarti occorrerà sprecare uno dei due colpi\\.\n\n"
                    "_N\\.B\\. Verrai visto dal vecchio saggio come un potenziale cattivo, in quanto hai il potere di uccidere\\. Discolpati dalle "
                      "accuse verbalmente o, appunto, coi proiettili e polvere da sparo\\._",
    "Sindaco 🎖️": "*Sei il sindaco\\!* 🎖️\n\nGiochi per la fazione dei buoni\\. Puoi far valere la tua autorità cittadina rivelandoti quando ti pare "
                "e piace, ma da quel momento in poi il tuo voto varrà doppio\\. Se quindi non si è ancora deciso chi linciare con certezza, "
                "assicurati che pattino con te il voto, altrimenti potrebbe avvenire un delitto politico\\.\\.\\.\n\n"
                "_Postilla\\!\\! Il lupo imbroglione potrà fingersi te, tuttavia non avrà davvero le tue capacità\\. Se sei ancora in partita, "
                "dimostra a tutti chi sei davvero\\!_",
    "Monarca 👑": "*Sei il monarca\\!* 👑\n\nGiochi per la fazione dei buoni\\. Il popolo indeciso ha bisogno di qualcuno che prenda in mano "
                "la situazione e qui entri in ballo tu\\. Con la corona che brilla, il passo deciso e il portamento regale, ti puoi rivelare "
                "in partita e decidere chi linciare\\. Puoi farlo solo TU, il resto del villaggio resterà a contemplare la tua autorità\\. "
                "Stai attento però a valutare i pro e i contro, potresti attuare la pena di morte su un povero innocente\\.\n\n"
                "_Postilla\\!\\! Il lupo imbroglione potrà fingersi te, tuttavia non avrà davvero le tue capacità\\. Se sei ancora in partita, "
                "dimostra a tutti chi sei davvero\\!_",
    "Principe 💍": "*Sei il principe\\!* 💍\n\nGiochi per la fazione dei buoni\\. Ti sei stancato della monotona vita tra le mura del castello "
                "e sei andato a vivere nel villaggio, tuttavia porti ancora con te il tuo anello regale che puoi mostrare per evitare di essere "
                "linciato\\. Bada però che il tuo potere puoi usarlo solo una volta e l'unico con il quale il tuo potere non vale è il monarca "
                "quindi se vuole linciarti sii prudente a difenderti\\.",
    "Martire 🔰": "*Sei il martire\\!* 🔰\n\nGiochi per la fazione dei buoni\\. Ad inizio partita, nel bot, ti verrà chiesto per chi intendi morire "
                "in seguito\\. La dea bendata sarà la tua unica alleata, in quanto non saprai se morirai per qualcuno di buono o cattivo, sinché "
                "egli non si paleserà\\. Pensa te che spreco morire per un lupo\\! Aiuuuuuto\\.",
    "Prostituta 💋": "*Sei la prostituita \\(A\\.K\\.A Putty\\)\\!* 💋\n\nGiochi per la fazione dei buoni\\. Il mestiere più antico del mondo e non ancora "
                 "tassato dallo stato, sarà tuo per questa partita\\! Vai, donna di facili costumi e sbattiteli tutti\\. Per la prima notte ti "
                  "consigliamo di saltare, in quanto potresti far visita a qualche asessuale che ti farà fuori, troppo svogliato per copulare\\. "
                 "Durante il giorno però esponi TRE nomi in ordine sparso, indicando quindi al popolo a chi offrirai le tue favolose prestazioni\\. "
                 "Se tu dovessi morire, il resto del villaggio inizierà a linciare per primi proprio i tuoi nomi\\.",
    "Bella 💅🏻": "*Sei la bella\\!* 💅\n\nGiochi per la fazione dei buoni\\. Ma se sei accoppiato giochi per far vincere la coppia\\. "
                "La tua bellezza è un tratto un po’ infame, attirerà qualcuno nella tua rete, tanto da farlo innamorare e persino \\- "
                "eventualmente \\- morire per te\\. Ma andiamo per gradi\\."
                "Se qualcuno dei ruoli della notte indicati in parentesi \\(Lupi, Serial killer, Cacciatore di satanisti, Satanista \\(l’ultimo "
                "convertito\\), Prostituta, Angelo custode, Ladro, Predatore\\) proverà a farti visita, si innamorerà di te e tu non morirai\\. "
                "Tuttavia, se un altro ruolo cattivo verrà a bussare alla tua porta, a morire sarà il tuo innamorato, mentre tu resterai "
                "bella\\-mente comoda sul tuo divano a guardare consumarsi il delitto\\. Bello, no\\?",
    "Cupido 🏹":"*Sei cupido\\! 🏹*\n\nGiochi per la fazione dei buoni\\. Con le tue frecce fai innamorare due "
              "persone tra loro e le vite della coppia saranno legate fino alla morte, quando uno dei due verrà ucciso l'altro lo seguirà "
              "nell'aldilà per stare insieme per sempre\\. Quando avrai scelto la coppia informa tutti di averlo fatto, ma presta attenzione, "
              "non rivelare chi è la coppia che si ama, o cercheranno di ammazzarli subito\\.",
    "Alchimista 🍵":"*Sei l'alchimista\\!* 🍵\n\nGiochi per la fazione dei buoni\\. La tua materia preferita è chimica tanto che dal primo giorno "
                  "inizi a fare esperimenti strani e provi a trovare una pozione per curare la licantropia, ci metti qualche giorno ma non "
                  "appena sarà pronta avrai la possibilità di darla ad una persona\\. Fai attenzione però e  sii sicuro di darla alla persona "
                  "giusta o la pozione darà l'effetto contrario\\. Cercare di curare una persona che non è un lupo ti porterà alla morte e "
                  "traformerà quella persona in lupo, dandola invece alla persona giusta la curerai\\. Avvisa sempre quando stai dando la "
                  "pozione dicendo a chi la dai, in questo modo il popolo saprà come comportarsi\\.",
    "Massone 👷🏻‍♂️":"*Sei il massone\\!* 👷🏻‍♂️\n\nGiochi per la fazione dei buoni\\. Forse sarebbe meglio dire un massone, infatti, specialmente quando "
              "si è in tanti, è l'unico ruolo che possono avere piu giocatori e tutti quanti si conoscono tra loro, per cui se ci sono altri "
              "massoni saprai esattamente chi sono\\. Alla fine però non fai nulla di particolare, tranne organizzare qualche festicciola "
              "tra massoni ogni sera, ah e la festa è esclusiva, se qualcuno non si presenta beh probabilmente non è piu un massone, "
              "quindi meglio avvisare tutti della sua assenza\\.",
    "Ubriaco 🍺":"*Sei l'ubriaco\\!* 🍺\n\nGiochi per la fazione dei buoni\\. L'alcool di ieri sera forse era troppo e puzzi ancora di birra, "
              "meglio farsi una doccia\\. A parte bere dal mattino alla sera non fai molto, avvisa tutti che se ti cercano ti trovano al "
              "bar e chiedi se qualcuno vuole venirti a fare compagnia\\. Sicuramente non si presenteranno i lupi, hai bevuto così tanto "
              "che a mangiarti si ubriacherebbero anche loro e per una notte non potrebbero mangiare nessuno\\.",
    "Uomo Lupo 👱‍♂️🐺":"*Sei l'uomolupo\\!* 👱‍♂️🐺\n\nGiochi per la fazione dei buoni\\.Hai passato così tanto tempo in mezzo ai boschi che la peluria "
                "ti fa sembrare un lupo, non lo sei sia chiaro, non faresti male ad una formica, ma se il veggente decidesse di scrutarti "
                "ti vedrebbe come lupo quindi sii pronto a difenderti nel caso ti accusino oppure rivelati anticipatamente in modo da "
                "avvisare tutti\\.",
    "Traditore 🖕🏻":"*Sei il traditore\\!* 🖕🏻\n\nGiochi per la fazione dei buoni\\.\\.\\.Per ora\\. Sei per il momento un semplice contadino ma, "
                "come dice il nome, se tutti i lupi dovessero morire saresti pronto a tradire il popolo per unirti alla fazione nemica "
                "e mangiare chi prima giocava con te\\. Sii cauto nel rivelarti o verresti immediatamente linciato, nessuno vuole traditori "
                "nel gruppo\\.",
    "Maledetto 😾":"*Sei il maledetto\\!* 😾\n\nGiochi per la fazione dei buoni\\.\\.\\.Per ora\\. Sei per ora un semplice contadino ed apparirai "
                  "al bot in quanto tale, ma fai attenzione a non rivelarti perchè se vieni morso diventerai un lupo, e al popolo i lupi non piacciono quindi sii cauto\\. ",
    "Bambino Ribelle 👶🏻":"*Sei il bambino ribelle\\!* 👶🏻\n\nGiochi per la fazione dei buoni\\.\\.\\.Per ora\\. Ad inizio partita scegli un modello "
                      "al quale ispirarti ed, essendo ribelle, alla sua morte ti arrabbierai tanto da diventare un lupo ed unirti ai "
                      "cattivi tradendo così il popolo\\. Fa attenzione quindi, non dire di esserlo o il popolo non la prenderà bene e "
                      "deciderà di linciarti\\.",
    "Lupo 🐺": "*Sei un Lupo\\!* 🐺\n\nGiochi per la fazione dei, beh, Lupi\\.Hai l’arduo compito di decidere quale taglio di carne fa al caso "
                "tuo\\. Fiorentina\\? Spagnola\\? Mentre però sei fisso sul menù, occhio a chi sbricia sulle tue scelte\\. Opta sempre per "
                "fingerti vegetariano o vegano e mantenere all’oscuro la tua natura\\. Potresti avere dei compagni, ti verranno comunicati dal "
                "bot e vincerà la maggioranza riguardo la vostra povera vittima\\.",
    "Lupo Alfa 🐺⚡️": "*Sei il Lupo Alfa\\!* 🐺⚡️\n\nGiochi per la fazione dei Lupi\\. Sei anche tu uno del branco, ma la luna piena ti "
                        "dona poteri particolari, oltre ad essere il capo, la tua scelta potrebbe essere decisiva per espandere la tua "
                        "fazione\\. Infatti ogni volta che morderai qualcuno, avrai la l’occasione di infettarlo e trasformarlo in un tuo "
                        "simile\\. In quanto Alfa hai la necessità di non farti beccare, sii cauto e prudente nel rivelare il tuo ruolo di "
                        "copertura, ma senza destare troppi sospetti\\.",
    "Cucciolo di Lupo 🐺🐶": "*Sei il Cucciolo di Lupo\\!* 🐶\n\nGiochi per la fazione dei Lupi\\. Giochi per la fazione dei Lupi\\. "
                              "Sei piccolino e tenero\\. Quasi ti accarezzerebbero nel villaggio, non sapendo che in realtà la tua natura "
                              "è tanto feroce quanto quella dei tuoi compagni\\. Tuttavia questi ultimi ti venerano e proteggono, e "
                              "qualora \\- data la tua inesperienza dovessero scoprirti a mangiucchiare in giro, facendoti fuori \\- si "
                              "arrabbierebbero così tanto da uccidere due volte la notte seguente alla tua dipartita\\. Magari non è così "
                              "male che ti scoprano, eh\\?",
    "Lupo Imbroglione 🐑": "*Sei il Lupo Imbroglione\\!* 🐑\n\nGiochi per la fazione dei Lupi\\. Sei da così tanto all'interno del "
                            "villaggio che la tua esperienza ti permette di confonderti tra gli abitanti, ad ogni partita hai la possibilità "
                            "di rivelarti a tutti con un altro ruolo \\(Monarca, Sindaco oppure Fabbro\\) ma attenzione\\!\\! I tuoi poteri "
                            "saranno fittizi, cerca di non far capire agli abitanti il bluff o verrai linciato per furto d'identità\\.\n\n"
                            "_Consiglio\\: quando il ruolo che vi viene comunicato come “copertura” è in inglese, sarebbe meglio "
                            "non utilizzarlo, perché il suddetto potrebbe essere NON presente in partita\\. Con tale dubbio, quindi, "
                            "sarebbe più opportuno non rischiare\\._",
    "Licantropo 🐺🌕": "*Sei il Licantropo\\!* 🐺🌕\n\nGiochi per la fazione dei Lupi\\.Un po' come Remus, la luna piena è il tuo peggior "
                        "nemico\\! Ogni volta che essa brilla in cielo, la tua pelle si cospargerà di peli e delle zanne sbucheranno dalle "
                        "tue labbra\\. Nel fuso orario di Lupus, tuttavia, ogni notte ha la luna piena e tu non sarai un mago provetto "
                        "capace di procurarti da solo una pozione\\. Tuttavia dalla tua parte hai un po’ di fortune\\:\n\n"
                        "\\- Scrutato dal veggente verrai visto come un semplice contadino\\;\n"
                        "\\- Potrai beneficiare anche tu della pozione contro la licantropia, offerta dall’Alchemista\\. Ma occhio al "
                        "controgame\\! Non chiederla se sei ancora in branco\\.\n\n"
                        "Per il resto, vai e mangiali tutti e \\+11 ai grifondoro\\.\\. cioè volevo dire, ai lupi\\.",
    "Lupo Nero 🐺⚫️": "*Sei il Lupo Nero\\!* 🐺🌑\n\nGiochi inizialmente per te stesso\\. Isolato dal branco credi di essere superiore a tutti, "
                        "d’altronde fra misantropia e licantropie cambia poco, no\\?\n"
                        "Tuttavia per dimostrare che hai più stoffa, dovrai sconfiggere il Lupo Alfa\\; ogni notte lo cerchi in lungo e largo "
                        "per affrontarlo in duello e mettiamo il caso tu dovessi vincerlo\\? Beh, diventeresti il nuovo Lupo Alfa\\. "
                        "In caso contrario, tranquillo, apprezziamo il tentativo\\.\\. \\(e ciao ciao\\)\\!",
    "Angelo Caduto 👼🏻🐺": "*Sei l'Angelo Caduto\\!* 👼🏻🐺\n\nGiochi per la fazione dei Lupi\\. Un po’ come Lucifero, sei caduto dal paradiso "
                            "e hai però trovato una piscina gonfiabile a salvarti il cu\\.\\. le ali\\! Tuttavia ad aspettarti c’era il Lupo "
                            "Alfa, il quale col suo morso ti ha invitato gentilmente ad unirti al branco\\.  Ogni notte avrai dunque la "
                            "possibilità di scegliere se uccidere un giocatore oppure proteggere un lupo, fa la scelta giusta e porta alla "
                            "gloria la tua \\(nuova\\) fazione\\!",
    "Predatore 🦉": "*Sei il Predatore\\!* 🦉\n\nGiochi per la fazione dei Lupi\\. Il tuo passatempo preferito è appostarti fuori dalle case "
                    "degli altri per sbirciare dalla loro finestra, un po’ alla Edward Cullen\\. Un po' inquietante ma d'altronde ognuno ha "
                    "le sue passioni\\.\\. Questo hobby ti permette di capire chi è sveglio di notte, e se la fortuna sarà dalla tua parte, "
                    "potresti assistere ad uno sbranamento in diretta, vedendo i colpevoli e capire dunque i tuoi alleati\\. Mi raccomando "
                    "però\\.\\. se li scovi non dire che sono lupi, ricorda che giocano con te\\.\n\n"
                    "_Avvertenza:\nNon tutti i ruoli svegli di notte sono lupi e non per forza sono cattivi quindi prestate attenzione_",
    "Stregone 🔮": "*Sei lo Stregone\\!* 🔮\n\nGiochi per la fazione dei Lupi\\. Forse il termine più corretto è veggente opposto, infatti "
                    "hai circa le sue stesse abilità ma giochi contro di lui\\. Ogni notte accarezzi la tua palla magica e hai la possibilità "
                    "di vedere un giocatore, capendo se è veggente oppure lupo\\; se sarai fortunato apparirà sul vetro della tua bolla di "
                    "vetro anche il ruolo preciso\\. Sii bravo a non farti scoprire, prendi al balzo la possibilità di fingerti veggente \\(se "
                    "non c’è osservatore, apprendista e veggente stesso\\) cercando di salvare e proteggere i tuoi lupi\\.",
    "Mago 🧙🏻‍♂️": "*Sei il Mago\\!* 🧙‍♂️\n\nGiochi per la fazione dei Lupi\\. Sicuramente appartenente alla casata dei Serpeverde, e in possesso "
                "di un tomo di arti oscure, decidi di schierarti dalla parte dei cattivi\\. Niente Voldemort, solo lupi questa volta\\. "
                "Il tuo compito è quello di marchiare quante più persone possibili di notte, scegliendo se disegnare una saetta sulle loro "
                "fronti o magari qualcos’altro di più originale\\! Ma bando alle ciance\\: se qualcuno di marchiato verrà morso da un lupo, "
                "si trasformerà in uno di loro\\. Attento però, il tuo marchio resta sinché sei in vita, perciò sii abile nello scovare il "
                "prossimo pesto del branco e precedili\\. Avada Kedavra\\!",
    "Sacerdote ✝️": "*Sei il Sacerdote\\!* ✝️\n\nGiochi per i Satanisti\\. Hai la tunica viola, il colletto bianco\\. Sei pronto per "
                      "la predica, ma sarà un po’ particolare\\.\\. difatti sei il capo della SETTA\\. Nessun “Hallelujah” piuttosto ci saranno "
                      "cori sinistri e da brivido\\. Il tuo potere è talmente elevato che puoi convertire anche chi ha meno probabilità "
                      "di essere portato nelle braccia dell’ignoto, nessuno desiste dalla tua tentazione\\. Usa questo potere con saggezza, "
                      "non farti scoprire e porta i satanisti alla vittoria\\.",
    "Satanista 👤": "*Sei il Satanista\\!* 👤\n\nGiochi per i satanisti\\. Tom Cruise e John Travolta sono tuoi compagni ma non sono "
                    "sufficienti, segui il gioco e ogni notte cerca di convertire chi è più probabile aderisca e segua il tuo culto\\. "
                    "Sta attento però a non andare dal cacciatore di satanisti o ci rimarrai secco, è il tuo peggior nemico e se lo visiti, "
                    "esporrai anche gli altri membri della setta\\. Non è l'unico ruolo che potrebbe ucciderti nel tentativo ingenuo di "
                    "convertirlo, altri ai quali devi prestare attenzione sono\\:\n\n\\- Cacciatore Urbano\\.\n\\- Serial Killer\\.\n\n"
                    "_Consiglio\\: I seguenti ruoli sono tra i più facilmente convertibili e che spesso troverai presenti in partita, "
                    "quindi ti consigliamo di partire da loro e fare attenzione a quando si rivelano\\: Contadino, Uomolupo, Fabbro, Cupido, "
                    "Sindaco, Monarca, Ubriaco, Vecchio Saggio, Oracolo, Scudiero \\(chiaramente prima che sussegua al Cacciasatana\\), "
                    "Portatore di Tempesta\\._\n\n"
                    "Occhio al linciaggio\\!\\!\\! Se un tuo compagno è malauguratamente finito fra i nomi da linciare, ma per numero siete "
                    "superiori voi Satanisti, patta il voto\\! Tuttavia se invece siete in minoranza, non destare sospetti e provvedi "
                    "magari a linciare qualcun altro o \\- nella peggiore delle ipotesi \\- proprio il tuo compagno\\. \\(Altrimenti "
                    "sarai il prossimo\\)\\.",
    "Serial Killer 🔪": "*Sei il Serial Killer\\!* 🔪\n\nGiochi quasi sempre da solo, tuttavia potrebbe capire tu abbia un compagno, lo Stalker Notturno\\."
                        "Ted Bundy è la tua chiara ispirazione, non serve dunque spiegare cosa farai in partita\\. O forse sì\\? Splatter a "
                        "pallettoni, un po’ di pugnali e tanta cattiveria, ecco ciò che caratterizza il tuo operato nel villaggio\\. "
                        "Ogni notte potrai mietere una vittima, purché non ci sia la tempesta, lasciarla priva di vita sul pavimento e "
                        "vendere i suoi organi sul deep web\\. Okay, forse non è un ruolo adatto ai minori di 18 anni\\.\\.\\. Ma passando "
                        "oltre \\(come le tue vittime\\, ahah _risata sinistra_\\), vinci se resti l’ultimo in partita o, come anticipato, "
                        "se vi è lo stalker notturno con te\\. Se sarai fortunato, non sarai tu a dover andare dai popolani ma loro verranno "
                        "a farti visita offrendosi come sacrifici\\. Che culo\\.\\. \\! \\:\\)",
    "Stalker Notturno 🦹‍♂️": "*Sei lo Stalker Notturno\\!* 🦹‍♂️\n\nGiochi per la fazione dei cattivi\\. In particolare sei il valido e "
                            "fidato compagno del Serial Killer \\(che coppia\\)\\. Se avete visto la miniserie Baby Reindeer è molto "
                            "semplice siete l'avvocatessa col barista ma senza mail scritte grammaticalmente in modo orribile e anzichè "
                            "voler far sesso con la vostra vittima voi volete ucciderla\\. Ho capito spiego per chi non ha visto la serie, "
                            "ogni notte vi mettete fuori dalla casa di un giocatore, se questo esce, zac \\(coltello che affonda\\), e avete "
                            "ucciso il giocatore, in caso contrario tornate a casa delusi e col coltello pulito\\. Mi raccomando non "
                            "rivelatevi o verrete denunciati per stalking \\(e forse anche omicidio\\)\\.",
    "Piromane 🔥": "*Sei il Piromane\\!* 🔥\n\nGiochi quasi sempre da solo e ogni tanto potrebbe esserci il tu compare burattinaio\\. Il "
                    "tuo peggior nemico è il corpo nazionale dei vigili del fuoco, infatti hai un compito semplice, avvaliti del tuo "
                    "lanciafiamme comprato da amazon alla modica cifra di 1599,99€ \\(spedizione esclusa\\) e dai fuoco a tutto cio che "
                    "incontri\\. Visto il prezzo alle stelle cerca di non fare brutte figure e di non farti scoprire subito, non vorrai "
                    "mica essere ricordato come il piromane che non riuscì ad incendiare\\.",
    "Burattinaio 🕴🏼": "*Sei il Burattinaio\\!* 🕴🏼\n\nGiochi con il Piromane, un'accoppiata strana infatti di comune avete poche cose, a "
                        "lui piace incendiare mentre a te, beh, diciamo che sei passato dal comandare le bambole di pezza e fare il "
                        "ventriloquo a comandare giocatori veri e fargli fare tutto ciò che vuoi\\. E se ci stai pensando, si puoi anche "
                        "controllare i lupi e decidere chi viene mangiato, un potere mica da buttare via \\(come la fine che hanno fatto "
                        "i tuoi bambolotti\\)\\. Non farti scoprire o il villaggio non sarà molto contento della notizia e potrebbero decidere "
                        "di farti fuori, sii cauto e buona controllata\\.",
    "MindBender 🧠 ": "*Sei il MindBender\\!* 🧠\n\nGiochi per la fazione dei buoni\\. Hai l'abilità di decidere ed eventualmente cambiare la "
                        "fazione di appartenenza di un giocatore\\. Mi spiego meglio, ogni giorno andate da una persona e se questa è cattiva "
                        "c'è la possibilità che la trasformiate in un contadino\\. Attenzione però che questa metamorfosi kafkiana ha durata "
                        "pari alla vostra vita, ciò significa che quando morirete verrà annullata e l'ex\\-cattivo tornerà ad essere tale\\. "
                        "Rivelatevi con cura, non vi consigliamo di farlo subito ed agire nell'ombra\\.",
    "Conciatore 👺": "*Sei il Conciatore\\!* 👺\n\nGiochi da solo\\. Il ruolo più amato e il ruolo più odiato da tutti\\. Ciò che devi fare "
                      "è semplicissimo, devi riuscire a farti linciare, come\\? Ah questo non lo so ce l'ho fatta forse solo una volta\\. "
                      "Quello che posso dirti è che non ci sono limiti a ciò che puoi dire o fare, attento però a non farti scoprire o avrai "
                      "una fine tragica e dolorosa\\. Sii bravo e trova la strategia giusta, divertiti a gettare un po' di chaos nel villaggio "
                      "e buona linciata\\.",
    "Ladro 😈": "*Sei il Ladro\\!* 😈\n\nGiochi da solo, almeno per ora\\. Cresciuto nei quartieri spagnoli di Napoli \\(non me ne vogliano "
                  "gli amici napoletani\\) sei cresciuto rubando prima delle caramelle, per poi passare ad oggetti più importanti come orologi "
                  "fino agli scooter\\. Ormai sei adulto e i soliti furti non ti piacevano così sei passato a rubare direttamente le identità "
                  "dei giocatori\\. Di notte hai infatti la possibilità di rubare il ruolo di un giocatore, se sei fortunato ti prendi "
                  "il ruolo, se ti va male e becchi il lupo o il serial killer beh, avrai una sepoltura degna di nota\\.\n\n"
                  "_Consiglio\\: Se iniziate con questo ruolo e non riuscite a rubare non ditelo subito, nel caso doveste rubare un ruolo "
                  "cattivo la vostra identità rimarrà un mistero\\._",
    "Sosia 🎭": "*Sei il Sosia\\!*  🎭\n\nGiochi da solo, almeno per ora\\. Ad inizio partita avete la possibilità di scegliere un giocatore "
                "che quando morirà copierete in tutto e per tutto, in particolare gli copierete il ruolo\\. Quando questo accadrà "
                "ripresentatevi a questo bot in quanto tali e vi daremo maggiori informazioni\\. Non abbiate paura di dire che siete sosia, "
                "per ora siete innocui\\.",
    "Negromante ⚰️": "*Sei il Negromante\\!*  ⚰️\n\nGiochi da solo, per ora\\. Vi diverte intrufolarvi nei cimiteri di notte e profanare "
                      "le tombe, un po' strano come passatempo ma non sono nessuno per giudicare\\. In ogni caso, il vostro compito è "
                      "semplice, ogni notte avete la possibilità di scegliere un giocatore tra quelli morti e prendere il suo ruolo, "
                      "quando ciò accadrà, presentatevi nuovamente al bot in quanto tale e vi diremo come comportarvi\\.\n\n"
                      "_N\\.B\\. Non siete obbligati a scegliere immediatamente un ruolo, potete aspettare la morte di qualcuno in "
                      "particolare oppure affidarvi all'istinto, è però importante che facciate la vista scelta entro fine partita\\._"
}


